import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function generateResultPdf({
  studentName,
  testName,
  score,
  rank,
  percentage
}: {
  studentName: string;
  testName: string;
  score: number;
  rank: number;
  percentage: number;
}) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawText("Sankalp Digital Pathshala", {
    x: 64,
    y: 760,
    size: 22,
    font: bold,
    color: rgb(0.08, 0.17, 0.28)
  });
  page.drawText("Result Report", { x: 64, y: 724, size: 16, font: bold });
  page.drawText(`Student: ${studentName}`, { x: 64, y: 680, size: 12, font });
  page.drawText(`Test: ${testName}`, { x: 64, y: 656, size: 12, font });
  page.drawText(`Score: ${score}`, { x: 64, y: 620, size: 14, font: bold });
  page.drawText(`Rank: ${rank}`, { x: 64, y: 596, size: 14, font: bold });
  page.drawText(`Percentage: ${percentage}%`, { x: 64, y: 572, size: 14, font: bold });
  page.drawText("Generated by Sankalp Digital Pathshala Test Portal", {
    x: 64,
    y: 96,
    size: 10,
    font,
    color: rgb(0.42, 0.46, 0.52)
  });

  return Buffer.from(await pdf.save());
}
